### PR TITLE
Update CI to check 1.6.4

### PR DESCRIPTION
**Pull request by konsumlamm**

### CODE REVIEW

**Comment by dlesnoff** [comment]
I am pretty sure `stable` version is already `1.6.2`.
I do not see why we should remove `1.6.0` support.

**Comment by konsumlamm** [comment]
True, stable is currently 1.6.2, so I guess checking 1.6 at all (or checking stable) is a bit redundant.

However, 1.6.2 is 1.6.0 with bug fixes, I don't see why we should keep 1.6.0 support.

**Comment by dlesnoff** [comment]
You are right, we should remove 1.6.0 support.

**Comment by narimiran** [comment]
Btw, 1.6.4 is around the corner.

**Comment by konsumlamm** [comment]
> Btw, 1.6.4 is around the corner.

So should I rather wait for that?

**Comment by narimiran** [comment]
> So should I rather wait for that?

Yeah, keep this open and once the 1.6.4 is out, we'll update and merge it.

**Comment by konsumlamm** [comment]
@narimiran since 1.6.4 is out now, I updated the PR. I also removed `stable`, since that's 1.6.4 anyway and this way we can explicitly state the supported versions.

**Review by dlesnoff — APPROVED** [review]

**Pull request merged**
